version: '3.6'
services:
  b2b-admin:
    image: b2b-admin
    restart: unless-stopped
    build:
      context: .
    expose:
      - "5000" 
    networks:
      - proxy-network
networks:
  proxy-network:
    external: true

