name: Deploy

# Trigger the workflow on push and
# pull request events on the production branch
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' # Only deploy when pushing to or merging pull request to 'master' or 'develop' branches
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          port: ${{ secrets.PROD_PORT }}
          key: ${{ secrets.PROD_SSHKEY }}
          script: |
            cd b2b-admin
            if [ "${{ github.ref }}" = "refs/heads/master" ]; then
              # Deployment for master branch
              git checkout master
              git pull origin master
            elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
              # Deployment for develop branch
              git checkout develop
              git pull origin develop
            fi
            docker compose down
            docker compose build
            docker compose up -d

      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          url=${{ secrets.PROD_HOST }}

          MESSAGE="🚀 Deployment Success! 🚀 %0A"
          MESSAGE+="├ Branch: ${{ github.ref }} %0A"
          MESSAGE+="├ Commit Message: ${{ github.event.head_commit.message }} %0A"
          MESSAGE+="├ Deployed by: ${{ github.actor }}%0A"
          MESSAGE+="├ Date and Time: $(date +'%Y-%m-%d %H:%M:%S') %0A"
          MESSAGE+="└ Deployment URL: $url %0A"

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=$MESSAGE"
